export const SEARCH_FOUCUS = 'header/SEARCH_FOUCUS'
export const HIDE_FOUCUS = 'header/HIDE_FOUCUS'
export const CHANGE_LIST = 'header/CHANGE_LIST'
export const MOUSE_LEAVE = 'header/MOUSE_LEAVE'
export const MOUSE_ENTER = 'header/MOUSE_ENTER'
export const CHANGE_PAGE = 'header/CHANGE_PAGE'
